name: Development build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'l10n_main'
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]

jobs:
  build:
    name: Development build
    runs-on: macos-14
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
          # - platform: 7
          #   platform_name: iossimulator
          # - platform: 8
          #   platform_name: tvossimulator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update
          brew install --cask temurin          # Latest (currently 24)
          brew install --cask temurin@17
          brew install --cask temurin@8
          brew install make
          brew install ldid
          export JAVA_HOME=$(/usr/libexec/java_home -v 17 || /usr/libexec/java_home -v 21)
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export RUNNER=1 SLIMMED=1
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          else
            make -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          fi

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa
